version: "3"
services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "80:80"
  rabbit:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "8080:15672"
      - "5672:5672"
  chat_postgres:
    image: postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: chat
  api:
    build: ./api
    restart: always
    ports:
      - "8000:8000"
    links:
      - rabbit
      - chat_postgres
    depends_on:
      - rabbit
      - chat_postgres
  websocket:
    build: ./ws_api
    restart: always
    ports:
      - "3000:3000"
    links:
      - rabbit
    depends_on:
      - rabbit